### ISSUE TITLE
Pypi releases

### ISSUE THREAD

**Issue by guewen** [OCA/odoo-sentinel#12]
Hi, 

Who have the superpowers to create new releases on Pypi?
There have been some nice pull requests merged since the last one.

**Comment by pedrobaeza** [comment]
The representative from Logistics PSC (@gurneyalex) or I think Logistics PSC (https://github.com/orgs/OCA/teams/logistics-maintainers)

**Comment by Garamotte** [comment]
Three PyPI accounts have Owner rights on this package on PyPI:
- alnsgara (myself), as I created this package
- laslabs (Dave Lasley)
- OCA, which seems to own all OCA's packages

**Comment by pedrobaeza** [comment]
@sylvain-garancher if this is correctly configured in .travis.yml, the deployment to Pypi is automatic when creating a new release here in GitHub. See an example in:

https://github.com/OCA/pylint-odoo/blob/cd9618133382f39790b847a886d1cb64acfc230f/.travis.yml#L57-L66

**Comment by sbidoul** [comment]
+1 to publish to pypi using travis when adding a new tag.

Another example [here](https://github.com/acsone/setuptools-odoo) or [here](https://github.com/acsone/click-odoo).

Side note: I highly recommend [setuptools_scm](https://github.com/pypa/setuptools_scm) over pbr for computing version from git tag.

**Comment by fmdl** [comment]
some one can publish on pip ?

**Comment by gurneyalex** [comment]
@sylvain-garancher ping

**Comment by rousseldenis** [comment]
I'll try to do it as indeed there are so much changes since 1.0 version.

**Comment by rousseldenis** [comment]
We'll manage automatic updates on pypi like in other repos with @sbidoul within few days

**Comment by rousseldenis** [comment]
@gurneyalex @fmdl @guewen @pedrobaeza  New release is online. Thanks to @sbidoul

**Comment by sbidoul** [comment]
Done in #16

**Comment by fmdl** [comment]
thank !

**Comment by fmdl** [comment]
cc @alnslang
