### ISSUE TITLE
Fix the CHANGES.txt file

### ISSUE THREAD

**Issue by Garamotte** [OCA/odoo-sentinel#4]
@lasley When you'll release a new version on PyPI, do not forget to clean the `CHANGES.txt` file... I created the package too quickly, and copied this file from the `zpl2` package without changing its contents :)

**Comment by lasley** [comment]
@sylvain-garancher - What's the point of this file vs. using release notes in tags?

**Comment by Garamotte** [comment]
If you are talking about GitHub's release notes: I wanted to have a changelog versionned in the git repo and/or easily accessible without relying on GitHub.

**Comment by lasley** [comment]
@sylvain-garancher - I'm more referring to mechanisms within Git, not Github. If we maintain a solid commit history, as well as use [Annotated Tags in Git](https://git-scm.com/book/en/v2/Git-Basics-Tagging#_annotated_tags), we maintain an implicit changelog without the addition of another file. These mechanisms are already in use for the release cycle, so IMO it's better to drop the file (#5).

_Edit: link to docs_
